default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: 1234
  host: localhost
  pool: 5

development:
  <<: *default
  database: mini_social_development

test:
  <<: *default
  database: mini_social_test

production:
  primary: &primary_production
    <<: *default
    database: mini_social_production
    username: mini_social
    password: <%= ENV["MINI_SOCIAL_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mini_social_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mini_social_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mini_social_production_cable
    migrations_paths: db/cable_migrate
